### ISSUE TITLE
Website is inaccessible due to certificate issue.

### ISSUE THREAD

**Issue by Swordington** [discordextremelist/lgbt-website#9]
**Describe the Bug**
Upon attempting to connect I get the error:
`ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

**Steps to Reproduce**
1. Open the website in a modern web browser

**Expected Behavior**
You should be able to access the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/25911649/105792983-2dbdf680-5f3d-11eb-8e42-8940502fa08a.png)

**Environment**

- OS: Windows 10
- Browser: Google Chrome
- Version: 87.0.4280.141 

**Additional context**
Assuming this is Let's Encrypt dying?

**Comment by advaith1** [comment]
yeah cloudflare dns seems to be broken on this unreleased short domain for some reason; updated the github repo link to the direct site url

**Comment by advaith1** [comment]
actually it should work now, does it work for you? (try in incognito)

**Comment by Swordington** [comment]
Looks like it's fixed! I love that .gay is a valid TLD.
